### PR TITLE
Start of 1.9 dev

### PR DESCRIPTION
**Pull request by PizzaCrust**
This pull requests contains:
- Gradle changes 
1. Adding **DeobfMC** as Gradle plugin to deobfuscate Minecraft (no need for more complicated setup, simply clone and run **applySpecialSource** to setup contribution workspace)
2. **Dependencies** is now managed by **Gradle**.
- Code Changes
1. Quantum Agent - a **initialization** option for Quantum API
- Compiling Changes
1. Tons of compile errors from going to **1.8 -> 1.9**. (**90** errors+)

### CODE REVIEW

**Comment by Caritas-Dei** [comment]
I think for now it would be best if people contribute to cold sections of the project such as gradle. If you'd like, @PizzaCrust, I can add you to the team and you can manage gradle (@code you need to talk to me!).

I personally find the fact that gradle removes IDE dependency a great thing, but also somewhat too complex, and thus I have no interest in learning Gradle. I would rather someone else handle it or I make my own simpler-with-more-options environment setter upper. Again, I don't like learning a large framework just to do one simple task.

**Comment by Caritas-Dei** [comment]
@EzraEn1 ^**

**Comment by PizzaCrust** [comment]
@LinkTheProgrammer 
I would love to manage Gradle. (I have just started reformatting my Gradle plugin for QuantumAPI)

**Comment by PizzaCrust** [comment]
I guess merge?

**Comment by Caritas-Dei** [comment]
A few changes need to be made before merge:
- we will work on 1.8 first before we move on.
  -DeobfMC will not be needed. If someone wants to make base edits with my API, they'll have to use MCP to decompile and deobfuscate minecraft source, as I will be making a medium for modding the base built on top of Mixin.
  -remove the minecraft and javassist dependencies. Developers won't need those.

If you were making this gradle project for development of Quantum API, I appreciate the offer, but I don't think we will need gradle to build this. If you want to make a gradle for the team, make a new branch "gradle".

**Comment by PizzaCrust** [comment]
DeobfMC is not for base edits. It adds Minecraft as a dependency.
It has benefits:
- MCP is no longer required for deobfuscation. Mappings can be provided directly by QuantumAPI contributors. Allowing for faster releases.
- MCP is also no longer required for obfuscating, too. Mappings can be reversed by DeobfMC.
- Developers no longer need to add MCP's client source or client's dependencies.

**Comment by Caritas-Dei** [comment]
Would you consider giving DeobfMC to QuantumTheoryMC?

**Comment by PizzaCrust** [comment]
Sure.

**Comment by Caritas-Dei** [comment]
Thank you! Would you mind transferring the repository please?

**Comment by PizzaCrust** [comment]
Transferred. We should transfer this chat. Trello, Skype, Email?

**Comment by Caritas-Dei** [comment]
Slack. What's your email?

**Comment by PizzaCrust** [comment]
pizzacrustcoder@gmail.com

**Comment by Caritas-Dei** [comment]
Check your email

**Comment by PizzaCrust** [comment]
I'm on it. (slack)

**Comment by PizzaCrust** [comment]
this pull request is no longer needed.

**Pull request closed without merging**
